### PR TITLE
integrates server columns into the theme.

### PR DESCRIPTION
**Pull request by AnonymousOne0680**
1 row is not enough

### CODE REVIEW

**Comment by PlusInsta** [comment]
Please do not use pull requests for suggestions. Closing without merging.

**Comment by AnonymousOne0680** [comment]
I added it into the css

**Comment by AnonymousOne0680** [comment]
just copy the source into custom css in bd

**Comment by AnonymousOne0680** [comment]
you will get 3 columns

**Comment by PlusInsta** [comment]
Nice try, thief.

https://github.com/mwittrien/BetterDiscordAddons/blob/master/Themes/ServerColumns/ServerColumns.css

**Pull request closed without merging**
