### PR TITLE
Fix new modals w/ banner

### PR DESCRIPTION
**Pull request by bonkmaykrQ**
### Before
Discord_NQfqul1sOq
### After
Discord_siEw55731A

### CODE REVIEW

**Comment by PlusInsta** [comment]
If merged, this would break the theme. Please make sure to disable plugins and use only the latest `DiscordPlus-source.theme.css` from `master` when making a pull request.

Closing this as invalid.

**Comment by bonkmaykrQ** [comment]
Thought the theme was supposed to auto-update? It has an @import.

**Comment by PlusInsta** [comment]
It sounds like you're misunderstanding how source code works.

`@import` is only utilized in the end-user theme file to pull the latest version of the source code from GitHub. When committing to the theme, you're making changes to that source code, not the automatically updating config-only end-user file.

Because you're editing the source code, you should make sure you don't have your customized version enabled, and that you've pulled all the latest changes from `master` after cloning the repo.

**Comment by bonkmaykrQ** [comment]
> It sounds like you're misunderstanding how source code works.
> 
> `@import` is only utilized in the end-user theme file to pull the latest version of the source code from GitHub. When committing to the theme, you're making changes to that source code, not the automatically updating config-only end-user file.
> 
> Because you're editing the source code, you should make sure you don't have your customized version enabled, and that you've pulled all the latest changes from `master` after cloning the repo.

I perfectly understood this already, but nothing in my custom CSS or .theme.css would've interfered with the new profile modals, I checked and it was 100% coming from the version in the Github repo, so I wrote a fix and put it into a commit. I'm not sure if Electron cached the old version and that broke it for me, but the latest version of the theme that Discord was downloading was not fixed.

**Comment by Notiphiliac** [comment]
If you have no CSS that clashes with a theme, it could likely be a plugin causing this as well. I am not having any overlap of the badges and avatar. The badges are on the left side of the profile in vanilla, while this is a theme, we try to keep it relatively vanilla as to not change the user experience or confuse people new to Discord.

**Pull request closed without merging**
